# Dockerfile.nginx
FROM nginx:alpine

# Copiem fișierul nostru de configurare Nginx
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copiem TOT codul (inclusiv vendor și public/build)
# din imaginea PHP (app-service) care a fost deja construită.
# MODIFICAT: Am schimbat numele serviciului de unde se copiază
COPY --from=calcul_deviz-app-service /var/www /var/www