# Dockerfile.nginx
FROM nginx:alpine

# Ștergem configurația implicită pentru a fi siguri că nu interferează
RUN rm -f /etc/nginx/conf.d/default.conf

# Copiem doar fișierul nostru de configurare Nginx.
# Volumul din docker-compose se va ocupa de codul sursă.
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf